function draw() {
  // create some nodes
  var nodes = [
    { id: "TC1", label: "Cálculo I", group: "Tronco Común" },
    { id: "TC2", label: "Algebra Superior I", group: "Tronco Común" },
    { id: "TC3", label: "Geometría Analítica Vectorial", group: "Tronco Común" },
    { id: "TC4", label: "Computación 1", group: "Tronco Común" },
    { id: "TC5", label: "Física General", group: "Tronco Común" },
    { id: "TC6", label: "Cálculo II", group: "Tronco Común" },
    { id: "TC7", label: "Algebra Superior II", group: "Tronco Común" },
    { id: "TC8", label: "Computación II", group: "Tronco Común" },
    { id: "TC9", label: "Física I", group: "Tronco Común" },
    { id: "TC10", label: "Cálculo I", group: "Tronco Común" },
    { id: "TC11", label: "Álgebra Lineal I", group: "Tronco Común" },
    { id: "TC12", label: "Probabilidad y Estadística", group: "Tronco Común" },
    { id: "TC13", label: "Ecuaciones Diferencias Ordinarias I", group: "Tronco Común" },
    { id: "TC14", label: "Cálculo II", group: "Tronco Común" },
    { id: "TC15", label: "Cálculo IV", group: "Tronco Común" },
    { id: "TC16", label: "Álgebra Lineal II", group: "Tronco Común" },
    { id: "120", label: "120 Créditos en TC", group: "Tronco Común" },
    
    { id: "C1", label: "Algortimos I", group: "Computación" },
    { id: "C2", label: "Análisis de Algoritmos", group: "Computación" },
    { id: "C3", label: "Lenguajes Formales", group: "Computación" },
    { id: "C4", label: "Computabilidad", group: "Computación" },
    { id: "C5", label: "Diseños Computacionales", group: "Computación" },
    { id: "C6", label: "Lenguajes de Programación", group: "Computación" },
    { id: "C7", label: "Geometría Computacional", group: "Computación" },
    { id: "C8", label: "Geometría Computacional II", group: "Computación" },
    { id: "C9", label: "Algoritmos Avanzados", group: "Computación" },
    { id: "C10", label: "Algoritmos Aleatorios", group: "Computación" },
    { id: "C11", label: "Procesamiento de Cadenas", group: "Computación" },
    { id: "C12", label: "Análisis de Algoritmos II", group: "Computación" },
    { id: "C13", label: "Complejidad", group: "Computación" },
    { id: "C14", label: "Álgebra Booleana", group: "Computación"},
    { id: "C15", label: "Diseño Digital", group: "Computación" },
    { id: "C16", label: "Teoría de Autómatas", group: "Computación" },
    { id: "C17", label: "Programación de Sistemas", group: "Computación" },
    { id: "C18", label: "Compiladores", group: "Computación" },
    { id: "C19", label: "Sistemas Operativos", group: "Computación" },
    { id: "C20", label: "Redes de computadora", group: "Computación" },
    { id: "C21", label: "Inteligencia Artificial", group: "Computación" },
    { id: "C22", label: "Introducción al Reconocimiento de Patrones", group: "Computación" },
    { id: "C23", label: "Procesamiento Digital de Imágenes", group: "Computación" },
    { id: "C24", label: "Graficación I", group: "Computación" },
    { id: "C25", label: "Interacción Hombre-Máquina", group: "Computación" },
    { id: "C26", label: "Seminario de Usabilidad", group: "Computación" },
    { id: "C27", label: "Interfaces de Usuario", group: "Computación" },
    { id: "C28", label: "Recuperación de Información", group: "Computación" },
    { id: "C29", label: "Bases de Datos", group: "Computación" },
    { id: "M1", label: "Análisis Matemático I", group: "Matemáticas" },
    { id: "M2", label: "Métodos Numéricos", group: "Matemáticas" },
    { id: "M3", label: "Geometría Euclidiana", group: "Matemáticas" },
    { id: "M4", label: "Álgebra Moderna", group: "Matemáticas" },
    { id: "M5", label: "Análisis Matemático II", group: "Matemáticas" },
    { id: "M6", label: "Teoría de Módulos ", group: "Matemáticas" },
    { id: "M7", label: "Análisis Complejo", group: "Matemáticas" },
    { id: "M8", label: "Topología", group: "Matemáticas" },
    { id: "M9", label: "Teoría de Conjuntos", group: "Matemáticas" },
    { id: "M10", label: "Geometría Diferencial", group: "Matemáticas" },
    { id: "M11", label: "Teoría de Números", group: "Matemáticas" },
    { id: "M12", label: "Matemáticas Discretas I", group: "Matemáticas" },
    { id: "M13", label: "Geometría Discretas I", group: "Matemáticas" },
    { id: "M14", label: "Geometría Moderna", group: "Matemáticas" },
    { id: "M15", label: "Ecuaciones Diferenciales Ordinarias II", group: "Matemáticas" },
    { id: "M16", label: "Análisis Funcional", group: "Matemáticas" },
    { id: "M17", label: "Topología Diferencial", group: "Matemáticas" },
    { id: "M18", label: "Teoría de Campos", group: "Matemáticas" },
    { id: "M19", label: "Introducción de Campos", group: "Matemáticas" },
    { id: "M20", label: "Introducción al Álgebra Homológica", group: "Matemáticas" },
    { id: "M21", label: "Topología de Conjuntos", group: "Matemáticas" },
    { id: "M22", label: "Matemáticas Discretas II", group: "Matemáticas" },
    { id: "M23", label: "Ecuaciones Diferenciales Parciales I", group: "Matemáticas" },
    { id: "M24", label: "Cálculo de Variaciones", group: "Matemáticas" },
    { id: "M25", label: "Ecuaciones Diferenciales Parciales II", group: "Matemáticas" },
    { id: "M26", label: "Geometría Proyectiva", group: "Matemáticas" },
    { id: "M27", label: "Lógica", group: "Matemáticas" },
    { id: "M28", label: "Teoría de Categorías", group: "Matemáticas" },
    { id: "M29", label: "Análisis Complejo II", group: "Matemáticas" },
    { id: "M30", label: "Álgebra Lineal Numérica", group: "Matemáticas" },
    { id: "M31", label: "Análisis Numérico I", group: "Matemáticas" },
    { id: "M32", label: "Análisis Numérico II", group: "Matemáticas" },
    { id: "M33", label: "Solución Numérica de Ecs Diferenciales Ordinarias", group: "Matemáticas" },
    { id: "M34", label: "Estadística I", group: "Matemáticas" },
    { id: "M35", label: "Estadística II", group: "Matemáticas" },
    { id: "M36", label: "Solución Numérica a Ecs Diferenciales Parciales", group: "Matemáticas" },
    { id: "M37", label: "Optimización", group: "Matemáticas" },
    { id: "M38", label: "Investigación de Operaciones", group: "Matemáticas" },

  ];
  // create some edges
  var edges = [
    

    { from: "TC8", to: "TC4" },
    { from: "C1", to: "TC7" },
    { from: "C1", to: "TC8" },
    { from: "C2", to: "C1" },
    { from: "C3", to: "TC4" },
    { from: "C3", to: "M4" },
    { from: "C3", to: "M27" },
    { from: "C4", to: "C3" },
    { from: "C4", to: "M8" },
    { from: "C5", to: "TC7" },
    { from: "C6", to: "TC4" },
    { from: "C7", to: "TC1" },
    { from: "C7", to: "TC3" },
    { from: "C8", to: "C7" },
    { from: "C9", to: "C2" },
    { from: "C10", to: "C2" },
    { from: "C11", to: "C1" },
    { from: "C12", to: "C2" },
    { from: "C13", to: "C2" },
    { from: "C13", to: "C4" },
    { from: "C14", to: "C5" },
    { from: "C15", to: "C14" },
    { from: "C16", to: "M4" },
    { from: "C16", to: "C27" },
    { from: "C17", to: "C3" },
    { from: "C17", to: "C15" },
    { from: "C18", to: "C7" },
    { from: "C19", to: "TC8" },
    { from: "C20", to: "C15" },
    { from: "C21", to: "TC10" },
    { from: "C21", to: "TC11" },
    { from: "C21", to: "TC13" },
    { from: "C21", to: "C6" },
    { from: "C22", to: "M34" },
    { from: "C22", to: "TC12" },
    { from: "C22", to: "TC16" },
    { from: "C23", to: "TC10" },
    { from: "C23", to: "TC16" },
    { from: "C23", to: "M34" },
    { from: "C23", to: "C1" },
    { from: "C24", to: "TC3" },
    { from: "C24", to: "C1" },
    { from: "C25", to: "TC8" },
    { from: "C26", to: "TC8" },
    { from: "C27", to: "TC8" },
    { from: "C28", to: "C1" },
    { from: "C28", to: "C11" },
    { from: "C29", to: "C1" },
    { from: "C29", to: "TC4" },
    { from: "M34", to: "TC6" },
    { from: "M34", to: "TC12" },
    { from: "M8", to: "M1" },
    { from: "M4", to: "TC11" },
    { from: "M27", to: "M9" },
    { from: "M9", to: "120" }, 
    { from: "M1", to: "TC10" }, 
    { from: "M1", to: "TC11" }, 
   
    
    //Materiás fuera del tronco principal que sin embargo podrían ser de utilidad 
    //Creo yo que metodos, modulos, categorias, Parciales, Alg lineal numérica
    //Optimización, Operaciones, Estadística I, II, Inv de operaciones
    { from: "M2", to: "TC6" }, 
    { from: "M2", to: "TC7" }, 
    { from: "M2", to: "TC8" }, 
    { from: "M6", to: "TC16" }, 
    { from: "M6", to: "M4" }, 
    { from: "M12", to: "TC2" }, 
    { from: "M23", to: "TC10" }, 
    { from: "M23", to: "TC13" }, 
    { from: "M30", to: "TC11" }, 
    { from: "M30", to: "M2" }, 
    { from: "M37", to: "TC15" }, 
    { from: "M37", to: "M1" }, 
    { from: "M38", to: "TC10" }, 
    { from: "M38", to: "TC11" }, 
    { from: "M35", to: "M34" }, 
  ];

  // create a network
  var container = document.getElementById("mynetwork");
  var data = {
    nodes: nodes,
    edges: edges,
  };
  var options = {
    edges:{
      arrows: 'from',


      scaling:{
        label: true,
      },

      smooth: true,
    },
    nodes: {
      shape: "dot",
      size: 16,
    },
    physics: {
      forceAtlas2Based: {
        gravitationalConstant: -26,
        centralGravity: 0.005,
        springLength: 230,
        springConstant: 0.18,
      },
      maxVelocity: 146,
      solver: "forceAtlas2Based",
      timestep: 0.35,
      stabilization: { iterations: 150 },
    },
  };
  var network = new vis.Network(container, data, options);
}

window.addEventListener("load", () => {
  draw();
});
